# Generated by Django 6.0.7 on 2026-08-12 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    models.EmailField(help_text="Укажите почту", max_length=254, unique=True, verbose_name="Email"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, help_text="Укажите телефон", max_length=20, null=True, verbose_name="Телефон"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, help_text="Укажите город", max_length=100, null=True, verbose_name="Город"
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите аватар",
                        null=True,
                        upload_to="users/avatars/",
                        verbose_name="Аватар",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, help_text="Укажите ФИО сотрудника", max_length=250, null=True, verbose_name="ФИО"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        help_text="Укажите должность сотрудника",
                        max_length=255,
                        null=True,
                        verbose_name="Должность",
                    ),
                ),
                (
                    "date_of_employment",
                    models.DateField(
                        default=datetime.date.today,
                        help_text="Укажите дату приема на работу",
                        verbose_name="Дата приема на работу",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Работает"),
                            ("vacation", "В отпуске"),
                            ("mission", "В командировке"),
                            ("sick_leave", "На больничном"),
                            ("dismissed", "Уволен"),
                        ],
                        default="active",
                        help_text="Укажите текущий статус сотрудника",
                        max_length=20,
                        verbose_name="Статус сотрудника",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Может ли пользователь входить в систему",
                        verbose_name="Активен в системе",
                    ),
                ),
                ("is_staff", models.BooleanField(default=False, verbose_name="Доступ к админке")),
                ("date_joined", models.DateTimeField(auto_now_add=True, verbose_name="Дата регистрации")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
                "ordering": ["-email"],
                "indexes": [
                    models.Index(fields=["email"], name="users_custo_email_c80f75_idx"),
                    models.Index(fields=["status"], name="users_custo_status_5faf9b_idx"),
                    models.Index(fields=["is_active"], name="users_custo_is_acti_1b62ea_idx"),
                    models.Index(fields=["is_staff"], name="users_custo_is_staf_3b7c79_idx"),
                ],
            },
        ),
    ]
