# Generated by Django 6.0.7 on 2026-08-02 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(
                        help_text="Введите наименование задачи", max_length=300, verbose_name="Наименование"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Подробное описание задачи", verbose_name="Описание задачи"
                    ),
                ),
                ("deadline", models.DateField(help_text="Укажите дату дедлайна", verbose_name="Срок выполнения")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Создана"),
                            ("processing", "В работе"),
                            ("completed", "Завершена"),
                            ("cancelled", "Отменена"),
                        ],
                        default="created",
                        help_text="Текущий статус выполнения задачи",
                        max_length=20,
                        verbose_name="Статус задачи",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Низкий"),
                            ("medium", "Средний"),
                            ("high", "Высокий"),
                            ("very_high", "Очень высокий"),
                        ],
                        default="low",
                        help_text="Важность задачи",
                        max_length=10,
                        verbose_name="Приоритет задачи",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Авто заполнение после завершения задачи",
                        null=True,
                        verbose_name="Дата завершения",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        help_text="Выберите сотрудника, ответственного за выполнение задачи",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Сотрудник",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        help_text="Кто создал задачу",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owner_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
                (
                    "parent_task",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите связанную родительскую задачу",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subtasks",
                        to="tasks.task",
                        verbose_name="Связанная задача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
                "ordering": ["-priority", "deadline"],
            },
        ),
    ]
